name: KSP2 Builder
description: 'An automated builder for KSP2 mods, that uses a skeleton dll.'
author: 'Sinon'

icon: check-square
color: yellow

runs: 
  using: composite
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
        
      - name: Build Project
        shell: bash
        run: dotnet build     
