name: KSP2 Builder
description: 'An automated builder for KSP2 mods, that uses a skeleton dll.'
author: 'Sinon'

icon: check-square
color: yellow

runs: 
  using: composite
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
        
      - name: Make external_dlls
        shell: bash
        run: mkdir ./external_dlls
        
      - name: Download Skeleton DLL
        shell: bash
        run: curl -o "./external_dlls/Assembly-CSharp.dll" "https://vortan.dev/ksp/spacewarp/DummyAssembly.dll"
        
      - name: Download Python Script
        shell: bash
        run: curl -o "./" "https://vortan.dev/ksp/spacewarp/runner.py"
        
      - name: Run Python Script
        shell: bash
        run: python runner.py
      
